"""
Working Memory Creation from Bbox Patches
Creates working memory representations using Vector Symbolic Algebra (VSA)
from bbox patches and coordinates generated by Code0GenerateBboxes.py
"""

import os
import numpy as np
import torch
import cv2
from PIL import Image
import torchvision.transforms as T
from natsort import natsorted
import sspspace

# Local imports
from load_model import EmbeddingExtractor

# Configuration paths
MODEL_PATH = "./autoencoder/patches_conv/best_model.ckpt"

ROOT = '/home/matt/DATA/CRIB/'
BBOX_BASE_PATH = ROOT + 'bboxes/'
MEMORY_SAVE_PATH = ROOT + 'workingmemory_from_bboxes/'

GAMMA = 0.99  # Memory update factor

class WorkingMemoryProcessor:
    """Processor for creating working memory from bbox patches and coordinates"""
    
    def __init__(self, model_path, device=None):
        # Setup device
        if device is None:
            self.device = torch.device(
                "mps" if torch.backends.mps.is_available()
                else "cuda" if torch.cuda.is_available()
                else "cpu"
            )
        else:
            self.device = device
            
        print(f"Using device: {self.device}")
        
        # Load model
        self.model = EmbeddingExtractor(model_path=model_path)
        
        # Initialize coordinate encoder (same dimensions as Code2CreatingWorkingMemory.py)
        self.coord_encoder = sspspace.RandomSSPSpace(domain_dim=2, ssp_dim=2500)
        
    def process_bbox_image(self, bbox_img_path, coordinate):
        """Process a single bbox image and coordinate pair"""
        # Load bbox image
        bbox_img = Image.open(bbox_img_path).convert('L')  # Convert to grayscale
        bbox_array = np.array(bbox_img)
        
        # Get features from the bbox image
        with torch.no_grad():
            image_features = self.model.get_embeddings(bbox_array)
        
        # Create spatial encoding from the original attention coordinate
        x, y = coordinate
        roi_center = self.coord_encoder.encode([[x, y]])
        img_feat_ssp = sspspace.SSP(image_features)
        
        # Bind coordinate and feature using VSA multiplication
        bound_representation = roi_center * img_feat_ssp
        
        return bound_representation, image_features
            
    def process_sequence(self, obj_name, seq_label, bbox_dir, coords_file):
        """Process all bbox images for a single sequence"""
        print(f"  Processing sequence: {obj_name}/{seq_label}")
        
        # Load coordinates
        coordinates = np.load(coords_file)
        print(f"    Loaded {len(coordinates)} coordinates")
        
        # Get all bbox images in this sequence directory
        bbox_files = natsorted([
            f for f in os.listdir(bbox_dir)
            if f.endswith('_roi.png') or f.endswith('_roi.jpg')
        ])
        
        if len(bbox_files) != len(coordinates):
            print(f"    Warning: Mismatch between bbox files ({len(bbox_files)}) and coordinates ({len(coordinates)})")
            min_len = min(len(bbox_files), len(coordinates))
            bbox_files = bbox_files[:min_len]
            coordinates = coordinates[:min_len]
            
        if len(bbox_files) == 0:
            print(f"    No bbox files found in {bbox_dir}")
            return None, None
            
        # Initialize sequence memory
        sequence_memory = self.coord_encoder.encode([[0, 0]])
        
        processed_count = 0
        for bbox_file, coord in zip(bbox_files, coordinates):
            bbox_path = os.path.join(bbox_dir, bbox_file)
            
            # Process bbox image with its coordinate
            bound_repr, image_features = self.process_bbox_image(bbox_path, coord)
            
            if bound_repr is not None:
                # Update memory using exponential decay
                sequence_memory = (GAMMA * sequence_memory +
                                   (1 - GAMMA) * bound_repr)
                processed_count += 1
                
            # Memory cleanup
            self._cleanup_memory()
            
        print(f"    Successfully processed {processed_count}/{len(bbox_files)} bbox images")
        return sequence_memory
        
    def process_object(self, obj_name, obj_bbox_path):
        """Process all sequences for a single object"""
        print(f"\nProcessing object: {obj_name}")
        
        # Get all sequence directories
        sequences = natsorted([
            d for d in os.listdir(obj_bbox_path)
            if os.path.isdir(os.path.join(obj_bbox_path, d)) and not d.startswith('.')
        ])
        
        if not sequences:
            print(f"  No sequences found for object {obj_name}")
            return
            
        object_memories = {}
        for seq_label in sequences:
            seq_dir = os.path.join(obj_bbox_path, seq_label)
            coords_file = os.path.join(seq_dir, f"{obj_name}_{seq_label}_coordinates.npy")
            
            if not os.path.exists(coords_file):
                print(f"  Coordinates file not found: {coords_file}")
                continue
                
            # Process this sequence
            seq_memory = self.process_sequence(
                obj_name, seq_label, seq_dir, coords_file
            )
            
            if seq_memory is not None:
                object_memories[seq_label] = seq_memory

        return object_memories

    def _cleanup_memory(self):
        """Clean up GPU memory"""
        if torch.backends.mps.is_available():
            torch.mps.empty_cache()
        elif torch.cuda.is_available():
            torch.cuda.empty_cache()

    def save_results(self, obj_name, object_memories, save_path):
        """Save processing results"""
        os.makedirs(save_path, exist_ok=True)
        
        # Save memories and features for each sequence
        for seq_label, memory in object_memories.items():
            memory_file = os.path.join(save_path, f'{obj_name}_{seq_label}_memory.npy')
            np.save(memory_file, memory)
                
        # Also save a combined memory (average of all sequences)
        if object_memories:
            combined_memory = sum(object_memories.values()) / len(object_memories)
            combined_file = os.path.join(save_path, f'{obj_name}_combined_memory.npy')
            np.save(combined_file, combined_memory)
            
        print(f"  ✅ Saved memories for {len(object_memories)} sequences of {obj_name}")


def main():
    """Main processing pipeline"""
    
    # Validate paths
    if not os.path.exists(MODEL_PATH):
        print(f"❌ Model path does not exist: {MODEL_PATH}")
        return
        
    if not os.path.exists(BBOX_BASE_PATH):
        print(f"❌ Bbox path does not exist: {BBOX_BASE_PATH}")
        return
        
    # Initialize processor
    processor = WorkingMemoryProcessor(MODEL_PATH)
        
    # Get objects to process
    objects = natsorted([
        d for d in os.listdir(BBOX_BASE_PATH)
        if os.path.isdir(os.path.join(BBOX_BASE_PATH, d)) and not d.startswith('.')
    ])
    
    if not objects:
        print(f"❌ No objects found in {BBOX_BASE_PATH}")
        return
        
    print(f"Found {len(objects)} objects to process: {objects}")
    
    # Process each object
    success_count = 0
    for obj in objects:
        obj_bbox_path = os.path.join(BBOX_BASE_PATH, obj)
        
        object_memories = processor.process_object(obj, obj_bbox_path)
        
        if object_memories:
            processor.save_results(obj, object_memories, MEMORY_SAVE_PATH)
            success_count += 1
        else:
            print(f"  No valid memories created for {obj}")
            
    print(f"\n✅ Processing complete!")
    print(f"Successfully processed: {success_count}/{len(objects)} objects")
    print(f"Results saved to: {MEMORY_SAVE_PATH}")


if __name__ == '__main__':
    main()
